language: python

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script: coverage run run_tests.py
after_success: coveralls
notifications:
  email: false
after_success: coveralls
